@startuml factory_uml

class SimulatorApplication
class SimulatorController
SimulatorController <|.. CanvasViewerController

class Factory
class ChargingStation {
    double chargingRate
    boolean isOccupied
    getChargingRate()
}

class Door {
    boolean isOpen
}
Door <|.. Component

interface Canvas
class Factory {
    Set<Observer> observers
    boolean simulationStarted
}
Factory <|-- Canvas
Factory <|.. Observable
Factory -> Robot
Factory -> Room
Factory -> ChargingStations

class Machine
Machine <|.. Component

class ProductionArea
ProductionArea -> Machine
ProductionArea <|.. Component 

class Robot {
   private double speed;
   private double energy;
   private double minEnergyLevel;
   private List<Component> componentsToVisit;
   private int currentTargetIndex;
}

BasicRectangleShape <|.. RectangleShape
BasicOvalShape <|.. OvalShape

Robot <|.. Component
interface Component 
Component <|.. Figure
SimulatorController -> Factory
SimulatorController -> CanvasPersistenceManager 

ChargingStation <|.. Component
@enduml
